version: '3'

services:
  db:
    image: postgres:alpine
    container_name: posthog_db_epresia
    environment:
      POSTGRES_USER: posthog
      POSTGRES_DB: posthog
      POSTGRES_PASSWORD: posthog
  redis:
    image: "redis:alpine"
    container_name: posthog_redis_epresia
  web:
    image: posthog/posthog:latest
    container_name: posthog_web_epresia
    ports:
      - "8010:8000"
      - "81:8000"
    environment:
      IS_DOCKER: "true"
      DATABASE_URL: "postgres://posthog:posthog@db:5432/posthog"
      REDIS_URL: "redis://redis:6379/"
      SECRET_KEY: "<randomly generated secret key>"
      IS_BEHIND_PROXY: "true"
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
